# https://taskfile.dev

version: '3'

vars:
  DOCKER_IMAGE: ghcr.io/brittonhayes/staffing

tasks:
  gen:
    desc: Generate Go from protobuf
    cmds:
      - buf generate
  docker:
    desc: Build docker image
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .