# https://taskfile.dev

version: '3'


tasks:
  gen:
    desc: Generate protobuf code
    cmds:
      - buf generate
  docker:
    desc: Build docker image
    cmds:
      - docker build -t ghcr.io/brittonhayes/staffing .