// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/department.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DepartmentCreateCommand with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DepartmentCreateCommand) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepartmentCreateCommand with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DepartmentCreateCommandMultiError, or nil if none found.
func (m *DepartmentCreateCommand) ValidateAll() error {
	return m.validate(true)
}

func (m *DepartmentCreateCommand) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return DepartmentCreateCommandMultiError(errors)
	}

	return nil
}

// DepartmentCreateCommandMultiError is an error wrapping multiple validation
// errors returned by DepartmentCreateCommand.ValidateAll() if the designated
// constraints aren't met.
type DepartmentCreateCommandMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepartmentCreateCommandMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepartmentCreateCommandMultiError) AllErrors() []error { return m }

// DepartmentCreateCommandValidationError is the validation error returned by
// DepartmentCreateCommand.Validate if the designated constraints aren't met.
type DepartmentCreateCommandValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepartmentCreateCommandValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepartmentCreateCommandValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepartmentCreateCommandValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepartmentCreateCommandValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepartmentCreateCommandValidationError) ErrorName() string {
	return "DepartmentCreateCommandValidationError"
}

// Error satisfies the builtin error interface
func (e DepartmentCreateCommandValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepartmentCreateCommand.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepartmentCreateCommandValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepartmentCreateCommandValidationError{}

// Validate checks the field values on DepartmentDeleteCommand with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DepartmentDeleteCommand) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepartmentDeleteCommand with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DepartmentDeleteCommandMultiError, or nil if none found.
func (m *DepartmentDeleteCommand) ValidateAll() error {
	return m.validate(true)
}

func (m *DepartmentDeleteCommand) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DepartmentId

	if len(errors) > 0 {
		return DepartmentDeleteCommandMultiError(errors)
	}

	return nil
}

// DepartmentDeleteCommandMultiError is an error wrapping multiple validation
// errors returned by DepartmentDeleteCommand.ValidateAll() if the designated
// constraints aren't met.
type DepartmentDeleteCommandMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepartmentDeleteCommandMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepartmentDeleteCommandMultiError) AllErrors() []error { return m }

// DepartmentDeleteCommandValidationError is the validation error returned by
// DepartmentDeleteCommand.Validate if the designated constraints aren't met.
type DepartmentDeleteCommandValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepartmentDeleteCommandValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepartmentDeleteCommandValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepartmentDeleteCommandValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepartmentDeleteCommandValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepartmentDeleteCommandValidationError) ErrorName() string {
	return "DepartmentDeleteCommandValidationError"
}

// Error satisfies the builtin error interface
func (e DepartmentDeleteCommandValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepartmentDeleteCommand.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepartmentDeleteCommandValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepartmentDeleteCommandValidationError{}
