// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/project.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectCreateCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProjectCreateCommand) Reset() {
	*x = ProjectCreateCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectCreateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateCommand) ProtoMessage() {}

func (x *ProjectCreateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateCommand.ProtoReflect.Descriptor instead.
func (*ProjectCreateCommand) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectCreateCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProjectCreateResponse) Reset() {
	*x = ProjectCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateResponse) ProtoMessage() {}

func (x *ProjectCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateResponse.ProtoReflect.Descriptor instead.
func (*ProjectCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectCreateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectCancelCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProjectCancelCommand) Reset() {
	*x = ProjectCancelCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectCancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCancelCommand) ProtoMessage() {}

func (x *ProjectCancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCancelCommand.ProtoReflect.Descriptor instead.
func (*ProjectCancelCommand) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectCancelCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectCancelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProjectCancelResponse) Reset() {
	*x = ProjectCancelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCancelResponse) ProtoMessage() {}

func (x *ProjectCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCancelResponse.ProtoReflect.Descriptor instead.
func (*ProjectCancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectCancelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectRenameCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProjectRenameCommand) Reset() {
	*x = ProjectRenameCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectRenameCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRenameCommand) ProtoMessage() {}

func (x *ProjectRenameCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRenameCommand.ProtoReflect.Descriptor instead.
func (*ProjectRenameCommand) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectRenameCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectRenameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProjectRenameResponse) Reset() {
	*x = ProjectRenameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectRenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRenameResponse) ProtoMessage() {}

func (x *ProjectRenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRenameResponse.ProtoReflect.Descriptor instead.
func (*ProjectRenameResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectRenameResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectRenameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_project_proto protoreflect.FileDescriptor

var file_proto_project_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x74, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x33, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x03, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x14,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x03, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x3b, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xc7,
	0x02, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x68, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x29, 0x2e, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x2a, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x29, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x1a, 0x2a, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68,
	0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x29, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x2a, 0x2e, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_project_proto_rawDescOnce sync.Once
	file_proto_project_proto_rawDescData = file_proto_project_proto_rawDesc
)

func file_proto_project_proto_rawDescGZIP() []byte {
	file_proto_project_proto_rawDescOnce.Do(func() {
		file_proto_project_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_project_proto_rawDescData)
	})
	return file_proto_project_proto_rawDescData
}

var file_proto_project_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_project_proto_goTypes = []interface{}{
	(*ProjectCreateCommand)(nil),  // 0: staffing.project.v1.ProjectCreateCommand
	(*ProjectCreateResponse)(nil), // 1: staffing.project.v1.ProjectCreateResponse
	(*ProjectCancelCommand)(nil),  // 2: staffing.project.v1.ProjectCancelCommand
	(*ProjectCancelResponse)(nil), // 3: staffing.project.v1.ProjectCancelResponse
	(*ProjectRenameCommand)(nil),  // 4: staffing.project.v1.ProjectRenameCommand
	(*ProjectRenameResponse)(nil), // 5: staffing.project.v1.ProjectRenameResponse
}
var file_proto_project_proto_depIdxs = []int32{
	0, // 0: staffing.project.v1.Project.CreateProject:input_type -> staffing.project.v1.ProjectCreateCommand
	2, // 1: staffing.project.v1.Project.CancelProject:input_type -> staffing.project.v1.ProjectCancelCommand
	4, // 2: staffing.project.v1.Project.RenameProject:input_type -> staffing.project.v1.ProjectRenameCommand
	1, // 3: staffing.project.v1.Project.CreateProject:output_type -> staffing.project.v1.ProjectCreateResponse
	3, // 4: staffing.project.v1.Project.CancelProject:output_type -> staffing.project.v1.ProjectCancelResponse
	5, // 5: staffing.project.v1.Project.RenameProject:output_type -> staffing.project.v1.ProjectRenameResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_project_proto_init() }
func file_proto_project_proto_init() {
	if File_proto_project_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_project_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectCreateCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectCancelCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectCancelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectRenameCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectRenameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_project_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_proto_goTypes,
		DependencyIndexes: file_proto_project_proto_depIdxs,
		MessageInfos:      file_proto_project_proto_msgTypes,
	}.Build()
	File_proto_project_proto = out.File
	file_proto_project_proto_rawDesc = nil
	file_proto_project_proto_goTypes = nil
	file_proto_project_proto_depIdxs = nil
}
