// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/project.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProjectCreateCommand with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectCreateCommand) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectCreateCommand with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectCreateCommandMultiError, or nil if none found.
func (m *ProjectCreateCommand) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectCreateCommand) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return ProjectCreateCommandMultiError(errors)
	}

	return nil
}

// ProjectCreateCommandMultiError is an error wrapping multiple validation
// errors returned by ProjectCreateCommand.ValidateAll() if the designated
// constraints aren't met.
type ProjectCreateCommandMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectCreateCommandMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectCreateCommandMultiError) AllErrors() []error { return m }

// ProjectCreateCommandValidationError is the validation error returned by
// ProjectCreateCommand.Validate if the designated constraints aren't met.
type ProjectCreateCommandValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectCreateCommandValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectCreateCommandValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectCreateCommandValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectCreateCommandValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectCreateCommandValidationError) ErrorName() string {
	return "ProjectCreateCommandValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectCreateCommandValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectCreateCommand.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectCreateCommandValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectCreateCommandValidationError{}

// Validate checks the field values on ProjectDeleteCommand with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectDeleteCommand) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectDeleteCommand with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectDeleteCommandMultiError, or nil if none found.
func (m *ProjectDeleteCommand) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectDeleteCommand) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return ProjectDeleteCommandMultiError(errors)
	}

	return nil
}

// ProjectDeleteCommandMultiError is an error wrapping multiple validation
// errors returned by ProjectDeleteCommand.ValidateAll() if the designated
// constraints aren't met.
type ProjectDeleteCommandMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectDeleteCommandMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectDeleteCommandMultiError) AllErrors() []error { return m }

// ProjectDeleteCommandValidationError is the validation error returned by
// ProjectDeleteCommand.Validate if the designated constraints aren't met.
type ProjectDeleteCommandValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectDeleteCommandValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectDeleteCommandValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectDeleteCommandValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectDeleteCommandValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectDeleteCommandValidationError) ErrorName() string {
	return "ProjectDeleteCommandValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectDeleteCommandValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectDeleteCommand.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectDeleteCommandValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectDeleteCommandValidationError{}
